ALTER TABLE departments ADD COLUMN chief_fio VARCHAR (100) not null after department_short_name;
ALTER TABLE departments ADD COLUMN chief_position VARCHAR (100) not null after chief_fio;

update departments set departments.chief_fio = 'Н.И. Холод' where department_short_name='РТС-1';
update departments set departments.chief_position = 'Начальник РТС-1' where department_short_name='РТС-1';
update departments set departments.chief_fio = 'В.В. Кравцов' where department_short_name='РТС-2';
update departments set departments.chief_position = 'Начальник РТС-2' where department_short_name='РТС-2';
update departments set departments.chief_fio = 'С.В. Балкис' where department_short_name='РТС-3';
update departments set departments.chief_position = 'Начальник РТС-3' where department_short_name='РТС-3';
update departments set departments.chief_fio = 'В.Н. Ромашкевич' where department_short_name='РТС-4';
update departments set departments.chief_position = 'Начальник РТС-4' where department_short_name='РТС-4';
update departments set departments.chief_fio = 'М.П. Лешкович' where department_short_name='РТС-5';
update departments set departments.chief_position = 'Начальник РТС-5' where department_short_name='РТС-5';
update departments set departments.chief_fio = 'С.М. Кохонов' where department_short_name='РТС-6';
update departments set departments.chief_position = 'Начальник РТС-6' where department_short_name='РТС-6';
update departments set departments.chief_fio = 'П.А. Руфкин' where department_short_name='РТС-7';
update departments set departments.chief_position = 'Начальник РТС-7' where department_short_name='РТС-7';
update departments set departments.chief_fio = 'В.А. Степанов' where department_short_name='ЭЛ';
update departments set departments.chief_position = 'Начальник ЭЛ' where department_short_name='ЭЛ';
update departments set departments.chief_fio = 'Е.О. Аркадьев' where department_short_name='САСУ и С';
update departments set departments.chief_position = 'Зам. начальника службы АСУ и связи' where department_short_name='САСУ и С';
update departments set departments.chief_fio = 'Н.Н. Кручок' where department_short_name='ТУ';
update departments set departments.chief_position = 'Начальник ТУ' where department_short_name='ТУ';
update departments set departments.chief_fio = 'С.М. Кандруцкий' where department_short_name='ПЦ';
update departments set departments.chief_position = 'Начальник ПЦ' where department_short_name='ПЦ';
update departments set departments.chief_fio = 'И.А. Шиманович' where department_short_name='ТЗУ';
update departments set departments.chief_position = 'Начальник ТЗУ' where department_short_name='ТЗУ';
update departments set departments.chief_fio = 'М.В. Явенко' where department_short_name='АРС';
update departments set departments.chief_position = 'Начальник АРС' where department_short_name='АРС';
update departments set departments.chief_fio = 'Ю.С. Милейковский' where department_short_name='СГМ';
update departments set departments.chief_position = 'Начальник СГМ' where department_short_name='СГМ';
update departments set departments.chief_fio = 'А.Н. Малышев' where department_short_name='СЭХ';
update departments set departments.chief_position = 'Начальник СЭХ' where department_short_name='СЭХ';
update departments set departments.chief_fio = 'М.А. Прокопович' where department_short_name='ЦС';
update departments set departments.chief_position = 'Начальник ЦС' where department_short_name='ЦС';
update departments set departments.chief_fio = 'Т.А. Вдовкина' where department_short_name='АХО';
update departments set departments.chief_position = 'Начальник АХО' where department_short_name='АХО';
